name: notes_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^3.0.3
  freezed: ^1.1.1
  injectable: ^1.5.3
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  flutter_hooks: ^0.18.2+1
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  freezed_annotation: ^1.1.0
  json_serializable: ^6.1.4
  rxdart: ^0.27.3
  dartz: ^0.10.1 
  form_field_validator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  injectable_generator: ^1.5.3
  build_runner: ^2.1.7
  hive_generator: ^1.1.2

flutter_intl:
  enabled: true 
  class_name: Localization
  arb_dir: lib/presentation/core/localization
  output_dir: lib/presentation/core/localization

flutter:
  uses-material-design: true